# Generated by Django 4.2.16 on 2024-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_pwd", models.CharField(max_length=100)),
            ],
        ),
    ]
